// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cinemate/DarkLuxury.tsx": () => import("../components/mockups/cinemate/DarkLuxury.tsx"),
  "./components/mockups/cinemate/Editorial.tsx": () => import("../components/mockups/cinemate/Editorial.tsx"),
  "./components/mockups/cinemate/Noir.tsx": () => import("../components/mockups/cinemate/Noir.tsx")
};
